language: node_js
node_js:
  - "node"

branches:
  only:
    - master

before_deploy:
  - test $TRAVIS_TEST_RESULT = 0 && npm run build

deploy:
  provider: surge
  project: ./public/
  domain: whiskeynot.es

